name: CI for WebDriverIO

on:
  push:
    branches:
      - main

jobs:
  wdio-build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.1.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run WebDriverIO tests
      - name: Run WebDriverIO
        run: npx wdio
