name: WebDriverIO CI with Allure Report

on:
  push:
    branches:
      - main  # Workflow ini berjalan setiap kali ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan pekerjaan ini di Ubuntu Latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mengambil kode dari repositori

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # Instalasi dependensi di package.json

      - name: Fix permissions
        run: chmod +x ./node_modules/.bin/wdio  # Memperbaiki izin untuk menjalankan wdio

      - name: Run WebDriverIO tests
        run: npx wdio  # Jalankan pengujian WebDriverIO menggunakan spec reporter

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.zip"
          unzip allure.zip -d allure
          sudo mv allure/allure-2.18.1 /usr/local/bin/allure
          allure --version  # Verifikasi bahwa Allure terpasang dengan benar

      - name: Generate Allure report
        run: |
          allure generate ./allure-results --clean -o allure-report
          
      - name: Upload Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./allure-report  # Direktori untuk laporan Allure
          github_token: ${{ secrets.GITHUB_TOKEN }}
